### ISSUE TITLE
Release BIRD Dev predicted sqls

### ISSUE THREAD

**Issue by CrZnGe** [ShayanTalaei/CHESS#1]
I am interested in your promising work. 
Could you release the predicted sqls (file) of BIRD-dev?

**Comment by nutor** [comment]
Hi authors, I am also interested in your work and your results. Is it possible to access your intermediate results (i.e., extracted keywords, etc.)? Thanks.

**Comment by vibl** [comment]
I would really be interested in the data too. I'm planning to publish an analysis of text-to-SQL methods that have published their code, in particular comparing their failure modes. Reproducing them would be time-consuming and expensive.

**Comment by ShayanTalaei** [comment]
Thank you all for your interest in our work and for your valuable feedback!

We’re happy to share that the results, including the predicted SQLs, intermediate outputs (e.g., extracted keywords), and full logs for the BIRD-dev set and other experiments, are now available in the `results/` directory on the repository.

Please feel free to reach out if you have any further questions or feedback.

**Comment by CrZnGe** [comment]
Thanks！
Best

**Comment by zhihui-shao** [comment]
> 谢谢！ 最好

Did you get an intermediate result? I can't find it now.

**Comment by lamaper** [comment]
> > 谢谢！ 最好
> 
> Did you get an intermediate result? I can't find it now.

In terms of time, the chess_on_dev.zip in branch chess-v1 may be the intermediate result provided by the author, which can be found in [CHESS/results/chess_on_dev.zip at chess-v1 · ShayanTalaei/CHESS](https://github.com/ShayanTalaei/CHESS/blob/chess-v1/results/chess_on_dev.zip).
