### ISSUE TITLE
Is there any way we can  use gpus with smaller CUDA memory to get the experiment result in the paper?

### ISSUE THREAD

**Issue by 652994331** [ShayanTalaei/CHESS#10]
HI , just wanna know is it possible to use gpu with smaller CUDA memory to get the same result mentioned in the paper?, like A100 with 40GB memory or 8*A40， A100 with 80GB memory is kind inaccessible though

**Comment by MohammadrezaPourreza** [comment]
Hi, sure you can. The scripts we provided assumes that we have access to a single A100 with 80GB memory, if you have a access to 8*A40 GPUs, you should be able to replicate the results but you have to use either DeepSpeed or FSDP for training on more than one GPU which requires some changes to the script.
