### ISSUE TITLE
[Bug] Accidentally pruned out Foreign Key.

### ISSUE THREAD

**Issue by asdf2024db** [ShayanTalaei/CHESS#11]
Hi, CHESS team.

We rerun your approaches all using GPT-3.5-Turbo and analysis all errors in generated SQL queries in BIRD before the repairing process. We found CHESS suffers from selecting correct ON condition to join two tables when generation step. After inspect the log of LLM, we believe the reason is that CHESS mistakenly prunes out foreign key columns or tables which are necessary for JOIN when constructing prompt, and thus the LLM lacks information to properly join tables. Your repairing process can compensate it for a bit since full schema are provided there.

**Comment by ShayanTalaei** [comment]
Hi,

Thanks for pointing this out! We also observed such a phenomenon in our runs. To accommodate for this case, we use the following protocols:

- As you mentioned, we provide the full schema in the revision step.
- We keep the connection columns (primary keys/foreign keys) among the selected tables in the schema, even if the LLM decides to drop them.
