### ISSUE TITLE
Cannot Run main.py

### ISSUE THREAD

**Issue by Tien-203** [ShayanTalaei/CHESS#13]
Hi, please help me address this issue.
When I run run_main.sh, it can run without any error but I dont see any result.
![image](https://github.com/user-attachments/assets/75c36aae-3f16-4c14-9d28-11395cee67aa)

**Comment by ShayanTalaei** [comment]
Sorry for the delay! There could be a few reasons why you’re not seeing any results after running `run_main.sh`. Without a clear error message, it’s challenging to debug. To gain more insight, I recommend setting `num_workers=1` in `run_main.sh` (to avoid multi-processing) and adjusting `log_level='info'` to monitor the steps as they execute.

I hope this helps! If you continue to experience issues, please feel free to follow up.
