### ISSUE TITLE
Vector Database

### ISSUE THREAD

**Issue by FrankPotter** [ShayanTalaei/CHESS#15]
Hello, the work you are doing is excellent！
 I would like to ask you if you can publicize the results of the data preprocessing after calling text-embedding-3-large, and I hope to hear from you!

**Comment by ShayanTalaei** [comment]
Thanks for your interest in our work! 
Unfortunately, it’s not feasible to share the embeddings directly (at least on GitHub), as they are similar in size to the databases. However, we’ve shared the code for preprocessing the database values and catalogs, and demonstrated how to run it via `run_preprocess.sh`. You can use the default embedding model to run this code (which is very cost-effective) or substitute any embedding model you prefer.

I hope this helps, and feel free to follow up if you have further questions!
