### ISSUE TITLE
bird evidence items

### ISSUE THREAD

**Issue by moore269** [ShayanTalaei/CHESS#19]
Do you use the bird evidence items as inputs as well?

evidence: the external knowledge evidence annotated by experts for assistance of models or SQL annotators.

**Comment by ShayanTalaei** [comment]
Yes, we pass both the questions and the evidence as inputs. According to the benchmark providers, each instance of the task comes with a pair of a question and an evidence which should be mapped to a SQL query. Using the evidence is a standard practice to clarify some of the disambiguities within the question.
