### ISSUE TITLE
How to Support Other LLMs

### ISSUE THREAD

**Issue by Lu-Boyan** [ShayanTalaei/CHESS#21]
How can I support other LLMs? Are there detailed steps and is it possible to switch to a local embedding model?
Thank you!

**Comment by Lu-Boyan** [comment]
Where can I find the specific URL for LLM requests? I couldn't locate the URL used for sending requests in the project.Otherwise, other LLMs cannot be used.

**Comment by ShayanTalaei** [comment]
Thanks for your question!

In https://github.com/ShayanTalaei/CHESS/blob/main/src/llm/engine_configs.py, we define the constructors of the models that we want to use in our system, in a modular way using the Langchain library. You can easily add any LLM of your choice to this file, and then set its name in the run_*.sh file accordingly. 

For switching to a local embedding model, you can similarly change the embedding models used in the preprocessing step, with the model of your choice. https://github.com/ShayanTalaei/CHESS/blob/main/src/database_utils/db_catalog/preprocess.py

**Comment by zhangnianlong** [comment]
> How can I support other LLMs? Are there detailed steps and is it possible to switch to a local embedding model? Thank you!

请问您修改成功了吗？能否分享一下怎么修改。谢谢

**Comment by zhangnianlong** [comment]
> How can I support other LLMs? Are there detailed steps and is it possible to switch to a local embedding model? Thank you!

Have you successfully made some modifications regarding the embedded model? Can you share how it was modified? thank you
