### ISSUE TITLE
how to obtain dev_gold.sql or train_gold.sql ?

### ISSUE THREAD

**Issue by ucalyptus2** [ShayanTalaei/CHESS#3]
@ShayanTalaei how do I obtain the BIRD benchmark file as mentioned in their readme?
https://github.com/AlibabaResearch/DAMO-ConvAI/issues/155

**Comment by ShayanTalaei** [comment]
You can obtain the BIRD benchmark files by downloading the dataset from the official [BIRD benchmark website](https://bird-bench.github.io/). For example, in the `dev.zip` file, you'll find a file named `dev.sql` that contains all the gold SQLs for the dev set.
