### ISSUE TITLE
How to use Checkpoint Feature?

### ISSUE THREAD

**Issue by JaviS-Rei** [ShayanTalaei/CHESS#4]
Hello, your work is very interesting. While reading your code, I noticed that you have implemented the Checkpoint Feature. My understanding of the Checkpoint Feature is that if I have already generated the 0th SQL statement, and all its log result files are saved in your default output folder, then upon enabling the Checkpoint Feature, it should skip the 0th statement and proceed directly to generate the 1st statement. However, the actual behavior seems to differ from my expectations. 

Therefore, **_I would like to ask how to correctly use your Checkpoint Feature_**, as it is not mentioned in the README.md.

Here is the modified run.sh script I used to start the Checkpoint Feature:
```sh
pipeline_nodes='keyword_extraction+entity_retrieval+context_retrieval+column_filtering+table_selection+column_selection+candidate_generation+revision+evaluation'
checkpoint_nodes='keyword_extraction+entity_retrieval+context_retrieval+column_filtering+table_selection+column_selection+candidate_generation+revision+evaluation'
checkpoint_dir="results/dev/keyword_extraction+entity_retrieval+context_retrieval+column_filtering+table_selection+column_selection+candidate_generation+revision+evaluation/dev/2024-07-17-21-25-45"

python3 -u ./src/main.py --data_mode ${data_mode} --data_path ${data_path}\
        --pipeline_nodes ${pipeline_nodes} --pipeline_setup "$pipeline_setup"\
        --use_checkpoint --checkpoint_nodes ${checkpoint_nodes} --checkpoint_dir ${checkpoint_dir}
```

**Comment by rocke2020** [comment]
Thanks for your paper and codes, I think it is a very good work for us. I hope to reproduce your codes.

[CHESS](https://github.com/ShayanTalaei/CHESS/tree/main)/[src](https://github.com/ShayanTalaei/CHESS/tree/main/src)/[runner](https://github.com/ShayanTalaei/CHESS/tree/main/src/runner)
/run_manager.py
In row 134 of run_manager.py, DatabaseManager() has not a function "get_db_schema()"

def load_checkpoint(self, db_id, question_id) -> Dict[str, List[str]]:
        tentative_schema = DatabaseManager().get_db_schema()

@ShayanTalaei Could you fix this? 
thanks very much in advance!!
