### ISSUE TITLE
How did you guys use the results from entity retrieval and context retrieval

### ISSUE THREAD

**Issue by 652994331** [ShayanTalaei/CHESS#8]
HI, how did you guys use results from entity retrieval and context retrieval . I saw this diagram 
<img width="1181" alt="截屏2024-09-26 17 45 45" src="https://github.com/user-attachments/assets/34dfed18-e4fa-427c-b8a1-a89535404e3b">
to my understanding , you used result from entity retrieval and context retrieval in the column filtering step, but when I looked at the prompt of  column filtering part, it's looks like it's a iterative process and you used this prompt  "column by column"  to check the relevance of columns and question, and I did not see entity and context part In this prompt.
<img width="1006" alt="截屏2024-09-26 17 46 50" src="https://github.com/user-attachments/assets/fe971572-184a-4a81-a49a-aa5a48bb5452">

**Comment by ShayanTalaei** [comment]
Hi, thanks for your questions, and sorry for the delayed reply!

For prompts with the database schema, we pass the retrieved entities and context as comments in the database schema for their corresponding column. For instance:

```
CREATE TABLE from
(
...
`County Name` TEXT null, -- Example Values: `Los Angeles`, 
`Free Meal Count (K-12)` REAL null, -- Column Description: Free Meal Count (K-12) | Value Description: eligible free rate = Free Meal Count / Enrollment,
...
) 
```

For the column filtering prompt specifically, we pass it in the COLUMN_PROFILE, which contains the table name, column name, the retrieved relevant values, and the context of that column.
